import '../styles/modern-normalize.css';
import '../styles/style.css';
import '../styles/components/header.css';
import '../styles/components/hero.css';
import '../styles/components/about.css';
import '../styles/components/service.css';
import '../styles/components/offer.css';
import '../styles/components/pricing.css';
import '../styles/components/more.css';
import '../styles/components/mobile-nav.css';
import '../styles/utils.css';
import mobileNav from './utils/mobile-nav';
import { animate } from './utils/scroll';
mobileNav();
animate();